export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES'
export const GET_COUNTRY_BY_ID = 'GET_COUNTRIES_BY_ID'
export const GET_COUNTRY_BY_NAME = 'GET_COUNTRIES_BY_NAME'

export const CREATE_ACTIVITY = 'CREATE_CONTINENTS'
export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES'

export const CLEAN_DETAIL = 'CLEAN_DETAIL'
export const CLEAN = 'CLEAN'

export const FILTER_CONTINENTS = 'FILTER_CONTINENTS'
export const FILTER_ACTIVITY = 'FILTER_ACTIVITY'

export const ORDER_COUNTRY = 'ORDER_COUNTRY'
export const ORDER_POPULATIONS = 'ORDER_POPULATIONS'